run_tag: '2048_tiny'
env_config: {
  env_type: '2048',
}
model_config: { # overwritten if loading a checkpoint
  input_size: [1, 4, 4],
  policy_size: 4,
  res_channels: 8,
  res_blocks: 2,
  value_head_res_channels: 8,
  value_head_res_blocks: 1,
  policy_head_res_channels: 8,
  policy_head_res_blocks: 1,
  kernel_size: 3,
  policy_fc_size: 32,
  value_fc_size: 32,
  value_output_activation: "tanh0to1"
}
train_mode_config: {
  algo_config: {
    name: "lazyzero",
    temperature: 1.0,
    num_policy_rollouts: 100,
    rollout_depth: 2,
    puct_coeff: 1.0,
  },
  learning_rate: 0.1,
  momentum: 0.8,
  c_reg: 0.0001,
  lr_decay_gamma: 0.9,
  replay_memory_max_size: 1000,
  replay_memory_min_size: 10,
  parallel_envs: 32,
  policy_factor: 1.0,
  minibatch_size: 256,
  episodes_per_epoch: 32,
  episodes_per_minibatch: 1,
  test_config: {
    algo_config: {
      name: "lazyzero",
      temperature: 0.0,
      num_policy_rollouts: 100,
      rollout_depth: 2,
      puct_coeff: 1.0,
    },
    episodes_per_epoch: 0
  }
}