run_tag: '2048_mini'
env_config: {
  env_type: '2048',
}
model_config: { # overwritten if loading a checkpoint
  input_size: [1, 4, 4],
  policy_size: 4,
  res_channels: 16,
  res_blocks: 6,
  value_head_res_channels: 16,
  value_head_res_blocks: 1,
  policy_head_res_channels: 16,
  policy_head_res_blocks: 1,
  kernel_size: 3,
  policy_fc_size: 32,
  value_fc_size: 32,
  value_output_activation: "tanh0to1"
}
train_mode_config: {
  algo_config: {
    name: "lazyzero",
    temperature: 1.0,
    num_policy_rollouts: 300,
    rollout_depth: 3,
    puct_coeff: 1.0,
  },
  learning_rate: 0.001,
  lr_decay_gamma: 0.9,
  replay_memory_max_size: 5000,
  replay_memory_min_size: 5000,
  parallel_envs: 4096,
  policy_factor: 1.0,
  minibatch_size: 1024,
  minibatches_per_update: 1,
  episodes_per_epoch: 5000,
  test_config: {
    algo_config: {
      name: "lazyzero",
      temperature: 0.0,
      num_policy_rollouts: 300,
      rollout_depth: 3,
      puct_coeff: 1.0,
    },
    episodes_per_epoch: 0
  }
}